# Generated by Django 2.0 on 2018-06-10 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='document',
            field=models.FileField(upload_to='video_folder/'),
        ),
    ]
