# Generated by Django 2.0 on 2018-07-25 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_auto_20180725_2138'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='image',
            field=models.FileField(default='/video_folder/nologo.png', upload_to='video_folder/'),
        ),
    ]
