# Generated by Django 2.0 on 2018-07-25 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.FileField(upload_to='video_folder/'),
        ),
    ]
