# Generated by Django 2.0 on 2018-07-11 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20180704_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='image',
            field=models.FileField(default='/pic_folder/nologo.png', upload_to='video_folder/'),
        ),
    ]
