# Generated by Django 2.0 on 2018-07-11 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0004_video_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='image',
            field=models.FileField(default='/video_folder/nologo.png', upload_to='video_folder/'),
        ),
    ]
