# Generated by Django 2.0 on 2018-07-24 17:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0010_employee'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='bio',
            field=models.CharField(default='NO BIO', max_length=500),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
