# Generated by Django 2.0 on 2018-07-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0011_auto_20180724_2014'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='location',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='bio',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
